# Generated by Django 4.0.2 on 2022-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultureplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('placeName', models.CharField(max_length=50)),
                ('lineNumber', models.CharField(max_length=15)),
                ('station', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=30)),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('hosun', models.CharField(max_length=15)),
            ],
        ),
    ]
